### ISSUE TITLE
Uanble to launch the application

### ISSUE THREAD

**Issue by Felys1998** [DeltaBreaker/Lolorito#1]
Running the application gives the error: `Error: A JNI error has occurred, please check your installation and try again` followed by `A Java Exception has occurred.`

JRE 1.8.0_333 x64 on Windows 11.

**Comment by Felys1998** [comment]
Worked after installing JDK 17.0.3.1; seems like your packaged exe is not properly targeting Java 8?

**Comment by DeltaBreaker** [comment]
Turns out it was actually an issue with the build path. Thanks for all the input! This one was quite important!
