### ISSUE TITLE
Crafting Data Broken after Dawntrial Update

### ISSUE THREAD

**Issue by RNGLilly** [DeltaBreaker/Lolorito#8]
Don't know if this is still being maintained, but the crafting profit and the crafting options seem to be broken, with the crafting profit showing N/A for every item and the crafting option only allowing Maximum Recipe Level: 1. 
![image_2024-08-02_164217334](https://github.com/user-attachments/assets/ebbbadf0-c406-436b-9175-ad1207835dd0)

**Comment by DeltaBreaker** [comment]
I've taken a break from the game which is why it hasn't been actively worked on, but I'll still look into issues like this when reported. Thank you for letting me know.

**Comment by RNGLilly** [comment]
Wonderful, thank you. Lolorito has been a huge help to me.

**Comment by DeltaBreaker** [comment]
Glad to hear it :)
Issue should be fixed with v5.1; was a problem with how recipe data was loaded.
